# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asd.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.domain_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.domain_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.domain_edit.setObjectName("domain_edit")
        self.horizontalLayout_6.addWidget(self.domain_edit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.search_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout_3.addWidget(self.search_bar)
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_3.addWidget(self.search_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(20, 0))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toon_list = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.toon_list.setFont(font)
        self.toon_list.setObjectName("toon_list")
        self.horizontalLayout_2.addWidget(self.toon_list)
        self.toon_view = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.toon_view.setFont(font)
        self.toon_view.setObjectName("toon_view")
        self.horizontalLayout_2.addWidget(self.toon_view)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pdf_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.pdf_btn.setChecked(True)
        self.pdf_btn.setObjectName("pdf_btn")
        self.verticalLayout.addWidget(self.pdf_btn)
        self.img_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.img_btn.setObjectName("img_btn")
        self.verticalLayout.addWidget(self.img_btn)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.down_btn = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.down_btn.setObjectName("down_btn")
        self.horizontalLayout_5.addWidget(self.down_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.search_btn.clicked.connect(MainWindow.search)
        self.down_btn.clicked.connect(MainWindow.crawling)
        self.search_bar.returnPressed.connect(self.search_btn.click)
        self.checkBox.stateChanged['int'].connect(MainWindow.all_checking)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.search_btn, self.toon_list)
        MainWindow.setTabOrder(self.toon_list, self.down_btn)
        MainWindow.setTabOrder(self.down_btn, self.domain_edit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "툰코 만화 수집기 Ver 0.35"))
        self.label_3.setText(_translate("MainWindow", "주소:"))
        self.domain_edit.setText(_translate("MainWindow", "https://toonkor.show"))
        self.label.setText(_translate("MainWindow", "Toonkor Collector"))
        self.label_2.setText(_translate("MainWindow", "Author: IML\n"
"email: shin10256@gmail.com\n"
"git: github.com\n/iml1111/Toonkor_Collector"))
        self.search_btn.setText(_translate("MainWindow", "검색"))
        self.checkBox.setText(_translate("MainWindow", "모두 선택"))
        self.pdf_btn.setText(_translate("MainWindow", "PDF 파일"))
        self.img_btn.setText(_translate("MainWindow", "이미지 파일"))
        self.down_btn.setText(_translate("MainWindow", "다운로드 시작"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

